---
httpd_server_config_name : default.conf
http_server_config_template : default.conf.j2
http_doc_root : /var/www/html
http_server_port : 80
http_server_admin : foo@bar.com
http_server_name : localhost
