---
- name: install php packages
  yum: pkg={{ item }} state=installed
  with_items:
   - "{{ php_packages }}"

- name: setup php.ini
  copy: src=php.ini dest=/etc/php.ini owner=root group=root mode=0644